CREATE TABLE USER (
    EMAIL VARCHAR(256) PRIMARY KEY,
    PASSWORD VARCHAR(256) NOT NULL,
    NAME VARCHAR(256) NOT NULL
);

CREATE TABLE CHATROOM (
    ID VARCHAR(512) PRIMARY KEY,
    MAX_PARTICIPANTS INTEGER NOT NULL DEFAULT 5 
);

CREATE TABLE CHAT (
    ID VARCHAR(512) PRIMARY KEY,
    CHATROOM_ID VARCHAR(512),
    FOREGIN KEY (CHATROOM_ID) REFERENCES CHATROOM(ID)
);

TRUNCATE TABLE USER;
TRUNCATE TABLE CHATROOM;
TRUNCATE TABLE CHAT;;
