CREATE TABLE USER (
    EMAIL VARCHAR(256) PRIMARY KEY,
    PASSWORD VARCHAR(256) NOT NULL,
    NAME VARCHAR(256) NOT NULL
);

CREATE TABLE CHATROOM (
    ID VARCHAR(256) PRIMARY KEY,
    MAX_PARTICIPANTS INTEGER NOT NULL DEFAULT 5,
);

CREATE TABLE CHAT (
    ID VARCHAR(256) PRIMARY KEY,
    CHATROOM_ID VARCHAR(256),
    USER_EMAIL VARCHAR(256),
    SENT_AT INTEGER NOT NULL DEFAULT 0,
    CONTENT TEXT NOT NULL DEFAULT 'X',
    FOREGIN KEY (CHATROOM_ID) REFERENCES CHATROOM(ID),
    FOREGIN KEY (USER_EMAIL) REFERENCES USER(EMAIL)
);

CREATE TABLE PARTICIPATION (
    
)

TRUNCATE TABLE USER;
TRUNCATE TABLE CHATROOM;
TRUNCATE TABLE CHAT;;
